version: "3.9"

services:
  db:
    image: neo4j:3.5
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./db/data:/data
      - ./db/logs:/logs
      - ./db/import:/var/lib/neo4j/import
      - ./db/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/test

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    container_name: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/code/
    environment:
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
      - NEO4J_BOLT_URL=bolt://neo4j:password@db:7687
      - NEOMODEL_MAX_CONNECTION_POOL_SIZE=50
    depends_on:
      - db

  frontend:
    container_name: frontend
    build: ./autodj
    volumes:
      - ./autodj:/app
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
      - db
